spring:
  application:
    name: sagent
  datasource:
    url: jdbc:h2:mem:sagent;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
  ai:
    model:
      embedding: transformers
    embedding:
      transformer:
        onnx:
          model-uri: classpath:/embedding/all-MiniLM-L6-v2/model.onnx
        tokenizer:
          uri: classpath:/embedding/all-MiniLM-L6-v2/tokenizer.json
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key: ${OPENROUTER_API_KEY:not-configured}
      chat:
        base-url: https://openrouter.ai/api/v1
        options:
          model: ${OPENROUTER_MODEL:openrouter/free}
    mcp:
      client:
        streamable-http:
          connections:
            mcpserver:
              url: http://localhost:8081/mcp

logging:
  level:
    org:
      springframework:
        ai: DEBUG
        chat:
         client:
           advisor: DEBUG
