server:
  port: 8081

spring:
  application:
    name: mcpserver
  ai:
    mcp:
      server:
        enabled: true
        protocol: STREAMABLE
        name: mcpserver
        version: 1.0.0
        streamable-http:
          mcp-endpoint: /mcp
logging:
  level:
    org:
      springframework:
        ai: DEBUG